let productsData = [
  {
    name: "The School of Life",
    description: "Book by Alain de Botton",
    price: 120000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1631377503l/58973006._SY475_.jpg",
    categoryId: 2,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Good to Great",
    description: "Book by Jim Collins",
    price: 220000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546097703l/76865.jpg",
    categoryId: 3,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "East of Eden",
    description: "Book by John Steinback",
    price: 90000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1639969375l/4406.jpg",
    categoryId: 1,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "inactive",
  },
  {
    name: "The Practice",
    description: "Book by Seth Godin",
    price: 190000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1598245238l/53479927.jpg",
    categoryId: 2,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "The Cartoon Introduction to Economics",
    description: "Book by Grady Klein",
    price: 450000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1416448134l/7333109.jpg",
    categoryId: 4,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Problem Solving 101",
    description: "Book by Ken Watanabe",
    price: 320000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1347726846l/6271219.jpg",
    categoryId: 4,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "The Obstacle is The Way",
    description: "Book by Ryan Holiday",
    price: 160000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1391440316l/18668059.jpg",
    categoryId: 2,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "archive",
  },
  {
    name: "Marketing",
    description: "Book by Brian Tracy",
    price: 70000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1392028225l/19148225.jpg",
    categoryId: 3,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "archive",
  },
  {
    name: "Cerpen Pilihan Kompas 2014",
    description: "Book by PENERBIT KOMPAS",
    price: 60000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1563511500l/35475838._SY475_.jpg",
    categoryId: 1,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Cerpen Pilihan Kompas 2015",
    description: "Book by PENERBIT KOMPAS",
    price: 80000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1464769336l/30328943._SX318_.jpg",
    categoryId: 1,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Rework",
    description: "Book by Jason Fried",
    price: 110000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1391275636l/6732019.jpg",
    categoryId: 3,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Mastery",
    description: "Book by Robert Greene",
    price: 350000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348274726l/13589182.jpg",
    categoryId: 2,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "The Icarus Deception",
    description: "Book by Seth Godin",
    price: 120000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1355795227l/15843041.jpg",
    categoryId: 2,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "The Daily Stoic",
    description: "Book by Ryan Holiday",
    price: 90000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1462161080l/29093292.jpg",
    categoryId: 2,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Zero To One",
    description: "Book by Peter Thiel",
    price: 290000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630663027l/18050143.jpg",
    categoryId: 3,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "The Lean Startup",
    description: "Book by Eric Ries",
    price: 90000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1629999184l/10127019._SY475_.jpg",
    categoryId: 3,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "All Marketers Are Liars",
    description: "Book by Seth Godin",
    price: 150000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1420382656l/160830.jpg",
    categoryId: 3,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "The Almanack of Naval Ravikant",
    description: "Book by Eric Jorgenson",
    price: 190000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1598011736l/54898389._SY475_.jpg",
    categoryId: 2,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Ego Is The Enemy",
    description: "Book by Ryan Holiday",
    price: 220000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1459114043l/27036528.jpg",
    categoryId: 2,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "This is Marketing",
    description: "Book by Seth Godin",
    price: 160000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1529247040l/40549476._SX318_.jpg",
    categoryId: 3,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Atomic Habits",
    description: "Book by James Clear",
    price: 390000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1535115320l/40121378._SY475_.jpg",
    categoryId: 2,
    authorId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "The Dip",
    description: "Book by Seth Godin",
    price: 130000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1311282216l/324748.jpg",
    categoryId: 3,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Purple Cow",
    description: "Book by Seth Godin",
    price: 140000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1309203098l/641604.jpg",
    categoryId: 3,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "The Infinite Game",
    description: "Book by Simon Sinek",
    price: 250000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1571114448l/38390751.jpg",
    categoryId: 3,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
  {
    name: "Senja dan Cinta yang Berdarah",
    description: "Book by Seno Gumira",
    price: 180000,
    imgUrl:
      "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1409371914l/23125037.jpg",
    categoryId: 1,
    authorId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "active",
  },
];

module.exports = productsData;
